#!/usr/bin/env bash
#
# UnrealEd Linux Launcher
#
# shellcheck source-path=SCRIPTDIR
# ARGBASH_SET_INDENT([  ])
# ARG_OPTIONAL_SINGLE([mode],[],[Informs the script on which Windows compatibility tool to use to launch UnrealEd],[auto])
# ARG_OPTIONAL_SINGLE([wine],[],[Path to wine (when using --mode=wine)],[])
# ARG_OPTIONAL_SINGLE([proton],[],[Path to proton compatibility tool (when using --mode=proton)],[])
# ARG_TYPE_GROUP_SET([mode],[MODE],[mode],[auto,umu-launcher,proton,wine])
# ARG_HELP([Launch UnrealEd])
# ARG_VERSION_AUTO([1.0],['OldUnreal <https://oldunreal.com>'])
# DEFINE_SCRIPT_DIR([_SCRIPT_DIR])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.11.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.dev for more info

die() {
  local _ret="${2:-1}"
  test "${_PRINT_HELP:-no}" = yes && print_help >&2
  echo "$1" >&2
  exit "${_ret}"
}

# validators

mode() {
  local _allowed=("auto" "umu-launcher" "proton" "wine") _seeking="$1"
  for element in "${_allowed[@]}"; do
    test "$element" = "$_seeking" && echo "$element" && return 0
  done
  die "Value '$_seeking' (of argument '$2') doesn't match the list of allowed values: 'auto', 'umu-launcher', 'proton' and 'wine'" 4
}

begins_with_short_option() {
  local first_option all_short_options='hv'
  first_option="${1:0:1}"
  test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_mode="auto"
_arg_wine=
_arg_proton=

print_help() {
  printf '%s\n' "Launch UnrealEd"
  printf 'Usage: %s [--mode <MODE>] [--wine <arg>] [--proton <arg>] [-h|--help] [-v|--version]\n' "$0"
  printf '\t%s\n' "--mode: Informs the script on which Windows compatibility tool to use to launch UnrealEd. Can be one of: 'auto', 'umu-launcher', 'proton' and 'wine' (default: 'auto')"
  printf '\t%s\n' "--wine: Path to wine (when using --mode=wine) (no default)"
  printf '\t%s\n' "--proton: Path to proton compatibility tool (when using --mode=proton) (no default)"
  printf '\t%s\n' "-h, --help: Prints help"
  printf '\t%s\n' "-v, --version: Prints version"
}

parse_commandline() {
  local _key
  while test $# -gt 0; do
    _key="$1"
    case "$_key" in
    --mode)
      test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
      _arg_mode="$(mode "$2" "mode")" || exit 1
      shift
      ;;
    --mode=*)
      _arg_mode="$(mode "${_key##--mode=}" "mode")" || exit 1
      ;;
    --wine)
      test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
      _arg_wine="$2"
      shift
      ;;
    --wine=*)
      _arg_wine="${_key##--wine=}"
      ;;
    --proton)
      test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
      _arg_proton="$2"
      shift
      ;;
    --proton=*)
      _arg_proton="${_key##--proton=}"
      ;;
    -h | --help)
      print_help
      exit 0
      ;;
    -h*)
      print_help
      exit 0
      ;;
    -v | --version)
      printf '%s %s\n\n%s\n%s\n' "unrealed-launch-linux.sh" "1.0" 'Launch UnrealEd' 'OldUnreal <https://oldunreal.com>'
      exit 0
      ;;
    -v*)
      printf '%s %s\n\n%s\n%s\n' "unrealed-launch-linux.sh" "1.0" 'Launch UnrealEd' 'OldUnreal <https://oldunreal.com>'
      exit 0
      ;;
    *)
      _PRINT_HELP=yes die "FATAL ERROR: Got an unexpected argument '$1'" 1
      ;;
    esac
    shift
  done
}

parse_commandline "$@"

# OTHER STUFF GENERATED BY Argbash
_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || {
  echo "Couldn't determine the script's running directory, which probably matters, bailing out" >&2
  exit 2
}
# Validation of values

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash

# Enable Bash Strict Mode
set -euo pipefail

unrealed::launcher() {
  declare -A ansi_colornum=(
    [black]=0
    [red]=1
    [green]=2
    [yellow]=3
    [blue]=4
    [magenta]=5
    [cyan]=6
    [white]=7
  )

  declare -A ansi_stylenum=(
    [reset]=0
    [bright]=1
    [dim]=2
    [italic]=3
    [underline]=4
    [flash]=5
    [highlight]=7
    [normal]=22
  )

  ansi::styled() {
    ALLOW_ESCAPES="off"
    if [[ "${1:-}" == "-e" ]]; then
      ALLOW_ESCAPES="on"
      shift
    fi

    local TEXT_TO_PRINT="${1:-}"
    local STYLE="${2:--1}"
    local FORE_COLOR="${3:--1}"
    local BACK_COLOR="${4:--1}"

    declare -a CODES RESETCODES
    if [[ "${STYLE}" -eq 22 ]] || [[ "${STYLE}" -eq -1 ]]; then
      RESETCODES=("$(printf "\033[%sm" "22")" "${RESETCODES[@]}")
    else
      CODES=("${CODES[@]}" "$(printf "\033[%sm" "${STYLE}")")
    fi

    if [[ "${BACK_COLOR}" -eq -1 ]]; then
      RESETCODES=("$(printf "\033[%sm" "49")" "${RESETCODES[@]}")
    else
      CODES=("${CODES[@]}" "$(printf "\033[%sm" "$((BACK_COLOR + 40))")")
    fi

    if [[ "${FORE_COLOR}" -eq -1 ]]; then
      RESETCODES=("$(printf "\033[%sm" "39")" "${RESETCODES[@]}")
    else
      CODES=("${CODES[@]}" "$(printf "\033[%sm" "$((FORE_COLOR + 30))")")
    fi

    local rc
    for rc in "${RESETCODES[@]}"; do
      echo -en "$rc"
    done
    local c
    for c in "${CODES[@]}"; do
      echo -en "$c"
    done

    if [[ "${ALLOW_ESCAPES}" == "on" ]]; then
      echo -en "${TEXT_TO_PRINT}"
    else
      echo -n "${TEXT_TO_PRINT}"
    fi

    echo -en "\033[m"
  }

  local OU_INSTALL_PATH
  OU_INSTALL_PATH="$(cd "$(dirname "${_SCRIPT_DIR}")" && pwd)" || {
    echo "Couldn't determine game installation directory." >&2
    exit 2
  }

  local PREFERRED_WINEPREFIX="${WINEPREFIX:-${OU_INSTALL_PATH}/.wine-unrealed}"

  unrealed::warning() {
    echo -e "$(ansi::styled "Warning:" "${ansi_stylenum[bright]}" "${ansi_colornum[yellow]}") $*" 1>&2
  }

  unrealed::error() {
    echo -e "$(ansi::styled "Error:" "${ansi_stylenum[bright]}" "${ansi_colornum[red]}") $*" 1>&2
  }

  local DEFAULT_PROTON="${HOME}/.steam/steam/steamapps/common/Proton - Experimental/proton"

  if [[ "${_arg_mode}" == "auto" ]]; then
    if [[ -n "${_arg_proton:-}" ]]; then
      _arg_mode="proton"
    elif [[ -n "${_arg_wine:-}" ]]; then
      _arg_mode="wine"
    fi

    if command -v umu-run &>/dev/null; then
      _arg_mode="umu-launcher"
    elif [[ -x "${DEFAULT_PROTON}" ]]; then
      _arg_mode="proton"
      _arg_proton="${DEFAULT_PROTON}"
    elif command -v wine &>/dev/null; then
      _arg_mode="wine"
      _arg_wine="wine"
    fi
  fi

  if [[ "${_arg_mode}" == "umu-launcher" ]]; then
    if ! command -v umu-run &>/dev/null; then
      unrealed::error "Unable to find umu-run in PATH."
      return 1
    fi

    local PREFERRED_PROTON="${_arg_proton:-${PROTONPATH:-}}"

    if [[ -z "${PREFERRED_PROTON}" ]]; then
      if [[ -x "/usr/share/steam/compatibilitytools.d/proton-ge-custom/proton" ]]; then
        PREFERRED_PROTON="/usr/share/steam/compatibilitytools.d/proton-ge-custom"
      else
        PREFERRED_PROTON="GE-Proton"
      fi
    fi

    cd "${OU_INSTALL_PATH}"
    WINEPREFIX="${PREFERRED_WINEPREFIX}" \
      GAMEID=umu-default \
      STORE=none \
      PROTONPATH="${PREFERRED_PROTON}" \
      exec umu-run "${_SCRIPT_DIR}/UnrealEd.exe"
  elif [[ "${_arg_mode}" == "proton" ]]; then
    if ! command -v "${_arg_proton}" &>/dev/null; then
      unrealed::error "--proton option is invalid."
      return 1
    fi

    cd "${OU_INSTALL_PATH}"
    STEAM_COMPAT_CLIENT_INSTALL_PATH="${STEAM_COMPAT_CLIENT_INSTALL_PATH:-~/.steam/steam}" \
      STEAM_COMPAT_DATA_PATH="${PREFERRED_WINEPREFIX}" \
      exec "${_arg_proton}" run "${_SCRIPT_DIR}/UnrealEd.exe"
  elif [[ "${_arg_mode}" == "wine" ]]; then
    if ! command -v "${_arg_wine}" &>/dev/null; then
      unrealed::error "--wine option is invalid."
      return 1
    fi

    unrealed::warning "Wine is untested, OldUnreal recommends running UnrealEd via Proton or UMU"

    cd "${OU_INSTALL_PATH}"
    WINEPREFIX="${PREFERRED_WINEPREFIX}" \
      exec "${_arg_wine}" "${_SCRIPT_DIR}/UnrealEd.exe"
  fi
}

unrealed::launcher
# ] <-- needed because of Argbash
