# shellcheck shell=bash

local ARCHITECTURE_SUFFIX ARCHITECTURE_BINARY_SUFFIX UE_SYSTEM_FOLDER_SUFFIX UEED_SYSTEM_FOLDER_SUFFIX

local DETECTED_ARCHITECTURE
DETECTED_ARCHITECTURE=$(uname -m)

case "${DETECTED_ARCHITECTURE}" in
x86_64 | amd64)
  case "${PRODUCT_SHORTNAME}" in
  UT2004)
    ARCHITECTURE_SUFFIX='amd64'
    ARCHITECTURE_BINARY_SUFFIX=''
    UE_SYSTEM_FOLDER_SUFFIX=''
    UEED_SYSTEM_FOLDER_SUFFIX=''
    ;;
  UnrealTournament)
    ARCHITECTURE_SUFFIX='amd64'
    ARCHITECTURE_BINARY_SUFFIX='-amd64'
    UE_SYSTEM_FOLDER_SUFFIX='64'
    UEED_SYSTEM_FOLDER_SUFFIX=''
    ;;
  *)
    ARCHITECTURE_SUFFIX='amd64'
    ARCHITECTURE_BINARY_SUFFIX='-amd64'
    UE_SYSTEM_FOLDER_SUFFIX='64'
    UEED_SYSTEM_FOLDER_SUFFIX='64'
    ;;
  esac
  ;;
aarch64)
  case "${PRODUCT_SHORTNAME}" in
  UT2004)
    ARCHITECTURE_SUFFIX='arm64'
    ARCHITECTURE_BINARY_SUFFIX=''
    UE_SYSTEM_FOLDER_SUFFIX='ARM64'
    UEED_SYSTEM_FOLDER_SUFFIX=''
    ;;
  UnrealTournament)
    ARCHITECTURE_SUFFIX='arm64'
    ARCHITECTURE_BINARY_SUFFIX='-arm64'
    UE_SYSTEM_FOLDER_SUFFIX='ARM64'
    UEED_SYSTEM_FOLDER_SUFFIX=''
    ;;
  *)
    ARCHITECTURE_SUFFIX='arm64'
    ARCHITECTURE_BINARY_SUFFIX='-arm64'
    UE_SYSTEM_FOLDER_SUFFIX='ARM64'
    UEED_SYSTEM_FOLDER_SUFFIX='64'
    ;;
  esac
  ;;
i386 | i686)
  case "${PRODUCT_SHORTNAME}" in
  UT2004)
    ARCHITECTURE_SUFFIX='NOT_SUPPORTED'
    ARCHITECTURE_BINARY_SUFFIX=''
    UE_SYSTEM_FOLDER_SUFFIX=''
    UEED_SYSTEM_FOLDER_SUFFIX=''
    ;;
  *)
    ARCHITECTURE_SUFFIX='x86'
    ARCHITECTURE_BINARY_SUFFIX='-x86'
    UE_SYSTEM_FOLDER_SUFFIX=''
    UEED_SYSTEM_FOLDER_SUFFIX=''
    ;;
  esac
  ;;
*)
  ARCHITECTURE_SUFFIX='NOT_SUPPORTED'
  ARCHITECTURE_BINARY_SUFFIX=''
  UE_SYSTEM_FOLDER_SUFFIX=''
  UEED_SYSTEM_FOLDER_SUFFIX=''
  ;;
esac
