#!/usr/bin/env bash
#
# Unreal Tournament 2004 Linux Installer
#
# shellcheck source-path=SCRIPTDIR
# ARGBASH_SET_INDENT([  ])
# ARG_OPTIONAL_SINGLE([destination],[d],[Install directory. Will be created if it doesn't exist.],[${XDG_DATA_HOME:-${HOME}/.local/share}/OldUnreal/UT2004])
# ARG_OPTIONAL_SINGLE([ui-mode],[],[UI library to use during install.],[auto])
# ARG_TYPE_GROUP_SET([uimode],[MODE],[ui-mode],[auto,kdialog,zenity,none])
# ARG_OPTIONAL_SINGLE([application-entry],[],[Action to take when installing the XDG Application Entry.],[prompt])
# ARG_OPTIONAL_SINGLE([desktop-shortcut],[],[Action to take when installing a desktop shortcut.],[prompt])
# ARG_TYPE_GROUP_SET([entryhandlingmode],[ACTION],[application-entry,desktop-shortcut],[install,prompt,skip])
# ARG_OPTIONAL_BOOLEAN([unrealed],[e],[Install UnrealEd (Windows, umu-launcher recommended).],[])
# ARG_OPTIONAL_BOOLEAN([keep-installer-files],[k],[Keep ISO and Patch files.],[])
# ARG_HELP([Install Unreal Tournament 2004])
# ARG_VERSION_AUTO([1.2],['OldUnreal <https://oldunreal.com>'])
# DEFINE_SCRIPT_DIR([_SCRIPT_DIR])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.11.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.dev for more info

die() {
  local _ret="${2:-1}"
  test "${_PRINT_HELP:-no}" = yes && print_help >&2
  echo "$1" >&2
  exit "${_ret}"
}

# validators

uimode() {
  local _allowed=("auto" "kdialog" "zenity" "none") _seeking="$1"
  for element in "${_allowed[@]}"; do
    test "$element" = "$_seeking" && echo "$element" && return 0
  done
  die "Value '$_seeking' (of argument '$2') doesn't match the list of allowed values: 'auto', 'kdialog', 'zenity' and 'none'" 4
}

entryhandlingmode() {
  local _allowed=("install" "prompt" "skip") _seeking="$1"
  for element in "${_allowed[@]}"; do
    test "$element" = "$_seeking" && echo "$element" && return 0
  done
  die "Value '$_seeking' (of argument '$2') doesn't match the list of allowed values: 'install', 'prompt' and 'skip'" 4
}

begins_with_short_option() {
  local first_option all_short_options='dekhv'
  first_option="${1:0:1}"
  test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_destination="${XDG_DATA_HOME:-${HOME}/.local/share}/OldUnreal/UT2004"
_arg_ui_mode="auto"
_arg_application_entry="prompt"
_arg_desktop_shortcut="prompt"
_arg_unrealed="off"
_arg_keep_installer_files="off"

print_help() {
  printf '%s\n' "Install Unreal Tournament 2004"
  printf 'Usage: %s [-d|--destination <arg>] [--ui-mode <MODE>] [--application-entry <ACTION>] [--desktop-shortcut <ACTION>] [-e|--(no-)unrealed] [-k|--(no-)keep-installer-files] [-h|--help] [-v|--version]\n' "$0"
  printf '\t%s\n' "-d, --destination: Install directory. Will be created if it doesn't exist. (default: '${XDG_DATA_HOME:-${HOME}/.local/share}/OldUnreal/UT2004')"
  printf '\t%s\n' "--ui-mode: UI library to use during install.. Can be one of: 'auto', 'kdialog', 'zenity' and 'none' (default: 'auto')"
  printf '\t%s\n' "--application-entry: Action to take when installing the XDG Application Entry.. Can be one of: 'install', 'prompt' and 'skip' (default: 'prompt')"
  printf '\t%s\n' "--desktop-shortcut: Action to take when installing a desktop shortcut.. Can be one of: 'install', 'prompt' and 'skip' (default: 'prompt')"
  printf '\t%s\n' "-e, --unrealed, --no-unrealed: Install UnrealEd (Windows, umu-launcher recommended). (off by default)"
  printf '\t%s\n' "-k, --keep-installer-files, --no-keep-installer-files: Keep ISO and Patch files. (off by default)"
  printf '\t%s\n' "-h, --help: Prints help"
  printf '\t%s\n' "-v, --version: Prints version"
}

parse_commandline() {
  local _key
  while test $# -gt 0; do
    _key="$1"
    case "$_key" in
    -d | --destination)
      test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
      _arg_destination="$2"
      shift
      ;;
    --destination=*)
      _arg_destination="${_key##--destination=}"
      ;;
    -d*)
      _arg_destination="${_key##-d}"
      ;;
    --ui-mode)
      test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
      _arg_ui_mode="$(uimode "$2" "ui-mode")" || exit 1
      shift
      ;;
    --ui-mode=*)
      _arg_ui_mode="$(uimode "${_key##--ui-mode=}" "ui-mode")" || exit 1
      ;;
    --application-entry)
      test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
      _arg_application_entry="$(entryhandlingmode "$2" "application-entry")" || exit 1
      shift
      ;;
    --application-entry=*)
      _arg_application_entry="$(entryhandlingmode "${_key##--application-entry=}" "application-entry")" || exit 1
      ;;
    --desktop-shortcut)
      test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
      _arg_desktop_shortcut="$(entryhandlingmode "$2" "desktop-shortcut")" || exit 1
      shift
      ;;
    --desktop-shortcut=*)
      _arg_desktop_shortcut="$(entryhandlingmode "${_key##--desktop-shortcut=}" "desktop-shortcut")" || exit 1
      ;;
    -e | --no-unrealed | --unrealed)
      _arg_unrealed="on"
      test "${1:0:5}" = "--no-" && _arg_unrealed="off"
      ;;
    -e*)
      _arg_unrealed="on"
      _next="${_key##-e}"
      if test -n "$_next" -a "$_next" != "$_key"; then
        { begins_with_short_option "$_next" && shift && set -- "-e" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
      fi
      ;;
    -k | --no-keep-installer-files | --keep-installer-files)
      _arg_keep_installer_files="on"
      test "${1:0:5}" = "--no-" && _arg_keep_installer_files="off"
      ;;
    -k*)
      _arg_keep_installer_files="on"
      _next="${_key##-k}"
      if test -n "$_next" -a "$_next" != "$_key"; then
        { begins_with_short_option "$_next" && shift && set -- "-k" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
      fi
      ;;
    -h | --help)
      print_help
      exit 0
      ;;
    -h*)
      print_help
      exit 0
      ;;
    -v | --version)
      printf '%s %s\n\n%s\n%s\n' "install-ut2004.sh" "1.2" 'Install Unreal Tournament 2004' 'OldUnreal <https://oldunreal.com>'
      exit 0
      ;;
    -v*)
      printf '%s %s\n\n%s\n%s\n' "install-ut2004.sh" "1.2" 'Install Unreal Tournament 2004' 'OldUnreal <https://oldunreal.com>'
      exit 0
      ;;
    *)
      _PRINT_HELP=yes die "FATAL ERROR: Got an unexpected argument '$1'" 1
      ;;
    esac
    shift
  done
}

parse_commandline "$@"

# OTHER STUFF GENERATED BY Argbash
_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || {
  echo "Couldn't determine the script's running directory, which probably matters, bailing out" >&2
  exit 2
}
# Validation of values

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash

# Enable Bash Strict Mode
set -euo pipefail

installer::entrypoint() {
  # Defining Installation Parameters
  local PRODUCT_NAME="Unreal Tournament 2004"
  local PRODUCT_SHORTNAME="UT2004"
  local PRODUCT_KEYWORDS=("UT2004" "UT2K4")
  local PRODUCT_URLSCHEME="ut2004"
  local MAIN_BINARY_NAME="UT2004"

  # Import Library files
  # @include lib/common.sh
  # @include lib/architecture.sh
  # @include lib/downloader.sh
  # @include lib/unarchiver.sh

  # Patch Metadata Download Step
  PATCH_METADATA_URL="https://api.github.com/repos/OldUnreal/UT2004Patches/releases"

  # Download Steps
  # shellcheck disable=SC2034 # Used dynamically below
  local TITLE_PRIMARY_DOWNLOAD_SOURCES=(
    "https://files.oldunreal.net/UT2004.ISO|2995322880|43e9182ae20bcbc0f6f4588fee6c1b336c261f1465403118a1973b09b1a22541"
    "https://files2.oldunreal.net/UT2004.ISO|2995322880|43e9182ae20bcbc0f6f4588fee6c1b336c261f1465403118a1973b09b1a22541"
    "https://files3.oldunreal.net/UT2004.ISO|2995322880|43e9182ae20bcbc0f6f4588fee6c1b336c261f1465403118a1973b09b1a22541"
  )

  # shellcheck disable=SC2034 # Used dynamically below
  local TITLE_BACKUP_DOWNLOAD_SOURCES=(
    "https://archive.org/download/ut-2004/UT2004.ISO|3751510016|7ae95242aa23d5e31b353811e1e920a4377fa53cf728b8edcb17006b7f3c4e97"
  )

  # Build Download sources
  declare -A DOWNLOADS_SOURCE_LIST=(
    [game]="$(downloader::build_download_source_definition "TITLE_PRIMARY_DOWNLOAD_SOURCES" "TITLE_BACKUP_DOWNLOAD_SOURCES")"
  )

  declare -A DOWNLOADS_FILENAME_LIST=(
    [game]="UT2004.iso"
  )

  # Game Data Unpacking
  # shellcheck disable=SC2034 # Used dynamically
  local UNPACK_IGNORE_PATTERNS=(
    # Old Setup Files
    'AutoRunData'
    'Disk1/layout.bin'
    'Disk1/Setup.*'
    'Disk1/setup.*'
    'SoNow'
    '*.*'
  )

  # @include steps/welcome_banner.sh
  step::welcome_banner

  # @include steps/check_dependencies.sh
  step::check_dependencies

  # @include steps/check_destination.sh
  step::check_destination

  # @include steps/eula.sh
  step::eula

  # @include steps/read_patch_meta_from_github.sh
  step::read_patch_meta_from_github
  if [[ "${_arg_unrealed}" == "on" ]]; then
    step::read_patch_meta_from_github "windows" "UnrealEd"
  fi

  # @include steps/download_files.sh
  step::download_files

  # @include steps/unarchive_generic.sh
  step::unarchive_generic "Game Files" "${_arg_destination%/}/Installer/${DOWNLOADS_FILENAME_LIST[game]}" "${_arg_destination%/}/Installer/.staging" "UNPACK_IGNORE_PATTERNS"

  # @include steps/ut2004_unpack_cabs.sh
  step::ut2004_unpack_cabs

  # @include steps/ut2004_install_files.sh
  step::ut2004_install_files

  if [[ "${_arg_unrealed}" == "on" ]]; then
    step::unarchive_generic "Latest Patch (UnrealEd)" "${_arg_destination%/}/Installer/${DOWNLOADS_FILENAME_LIST[patch_windows]}" "${_arg_destination%/}"
  fi
  step::unarchive_generic "Latest Patch" "${_arg_destination%/}/Installer/${DOWNLOADS_FILENAME_LIST[patch_linux]}" "${_arg_destination%/}"

  # @include steps/ut2004_special_fixes.sh
  step::ut2004_special_fixes

  # @include steps/create_unrealed_launcher.sh
  if [[ "${_arg_unrealed}" == "on" ]]; then
    step::create_unrealed_launcher
  fi

  # @include steps/xdg_desktop_entry.sh
  step::xdg_desktop_entry \
    "Application Menu Entry" \
    "Do you want to create an application menu entry?" \
    "${XDG_DATA_HOME:-${HOME}/.local/share}/applications/OldUnreal-${PRODUCT_SHORTNAME}.desktop" \
    "${XDG_DATA_HOME:-${HOME}/.local/share}/applications/OldUnreal-${PRODUCT_SHORTNAME}-UnrealEd.desktop" \
    "${_arg_application_entry}"

  step::xdg_desktop_entry::xdg_dir \
    "Desktop Shortcut" \
    "Do you want to create a shortcut on your desktop?" \
    "DESKTOP" \
    "${PRODUCT_SHORTNAME}.desktop" \
    "UnrealEd-${PRODUCT_SHORTNAME}.desktop" \
    "${_arg_desktop_shortcut}"

  # @include steps/notify_install_finished.sh
  step::notify_install_finished
}

installer::entrypoint
# ] <-- needed because of Argbash
